---
apiVersion: v1
kind: Pod
metadata:
  name: fosdemo
  labels:
    app: fosdemo
spec:
  securityContext:
    runAsUser: 0
    fsGroup: 0
  containers:
  - name: fosdemo-nginix
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: fosdemo-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fosdemo
  name: fosdemo
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-80
    nodePort: 30883
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fosdemo
  sessionAffinity: None
  type: NodePort
