apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fosdemo-data
  annotations:
      foo: bar
spec:
  dataSource:
    name: v1.0-populator
    kind: VolumePopulator
    apiGroup: populator.storage.k8s.io
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: hostpath
