---
apiVersion: v1
kind: Pod
metadata:
  name: gitd
  labels:
    app: gitd
spec:
  containers:
  - name: fosdemo-nginix
    image: aglitke/docker-git-server
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 22
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitd
  name: gitd-ssh
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 22-22
    nodePort: 30884
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: gitd
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitd
  name: gitd-http
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-80
    nodePort: 30880
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gitd
  sessionAffinity: None
  type: NodePort
